#!/bin/bash
# https://nilhcem.github.io/FakeSMTP/
# https://nilhcem.github.io/FakeSMTP/download.html

# Test if running with "bash" interpreter.
if [ -z "$BASH" ]; then
	bash "$0" "$@"
	exit $?
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
MAIL_PATH="$DIR/mails"
PORT="25"
H="$(cat /etc/hostname)"

if ! type mail &> /dev/null
	then
		sudo apt-get install mailutils
	fi

if [ ! -f "$DIR/fakeSMTP.jar" ]; then
	if ! type unzip &> /dev/null
		then
			echo "Installing unzip..."
			sudo apt-get install unzip
		fi

	CDIR="$(pwd)"
	cd $DIR
	wget -q http://nilhcem.github.com/FakeSMTP/downloads/fakeSMTP-latest.zip && \
		unzip fakeSMTP-latest.zip -d ./ && \
		rm -f fakeSMTP-latest.zip && \
		mv -v fakeSMTP-*.jar fakeSMTP.jar
	cd "$CDIR"
fi

if ! grep "$H" /etc/hosts > /dev/null
	then
		echo "Fix hosts file"
		echo "Add $H to host file"
		sudo echo "127.0.0.1 $H" > /etc/hosts
  fi

isUI=false
[ "$1" = "ui" ] && isUI=true

xsu() {
	if $isUI; then
		gksu --description "$1" "$2"
	else
		echo "Exec: $1"
		sudo $2
	fi
}

if ! $isUI ; then
	echo
	echo Satart fSMTP - FakeSMTP
	echo
	echo "Port:      $PORT"
	echo "Mail Path: $MAIL_PATH"
	echo "Test:      echo 'Hello world!' | mail -s 'Test mail' test@fsmtp.com"
	echo
fi

xsu "Stop SendMail" "service sendmail stop"
xsu "fSMTP - fakeSMTP" "java -jar $DIR/fakeSMTP.jar -s -p $PORT -o '$MAIL_PATH'"
